### ISSUE TITLE
scrape doesnt scrape members

### ISSUE THREAD

**Issue by Hackermanlmao** [Gowixx/OkuruNuker#10]
it just scrapes like one

**Comment by zCircleBallX** [comment]
It should work!

**Comment by Gowixx** [comment]
Do it again, also you need perms

**Comment by HeLLMan69** [comment]
Enable Intents on of your bot!
![Screenshot_20210603-002222_Chrome.png](https://user-images.githubusercontent.com/83206243/120536576-e6230c00-c401-11eb-8508-4b386b7cbf7c.png)

**Comment by Gowixx** [comment]
**Closing as no response was given**
